name: Build docker image

on:
  push:
    branches: ["**"]

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get short github sha
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: actions/setup-python@v5 
        with:
          python-version: '3.8' 
      - run: |
          pip install pyinstaller
          pip install staticx
          pyinstaller main.spec
          staticx ./dist/main/main ./app
          ls
      - name: Push to GitHub Packages
        id: "build-push-docker"
        uses: docker/build-push-action@v2
        env:
          SHA: steps.sha.outputs.sha_short
        with:
          push: true
          context: .
          file: ./docker/deploy/Dockerfile
          tags: ghcr.io/farizap/python-single-executable:latest,ghcr.io/farizap/python-single-executable:${{steps.sha.outputs.sha_short}}
